### ISSUE TITLE
Multiple Questions in One Thread

### ISSUE THREAD

**Issue by evenstensberg** [lencioni/ama#1]
**Q(1): How do you tackle server side rendering at Airbnb**

---

**Q(2): How do you proceed the back-end logic on the Machine Learning part from the Front-End part. Is there any key differences in terms of passing data into your React/Database components?**

---

**Q(3): Are you using Univariate Polarisation in some of the ML data/ Neural Networks ( ex: user could be a non-scammer, and then turn into a scammer and back to being a non-freud )**

---

**Q(4): How did you start of with programming? Any good stories to share on that part?**

---

**Q(5): Can you mention some of the technologies AirBnB uses besides React?**

---

**Q(6): Are you doing something similar to what Netflix do in their code? [Keynote from nodeJS](https://www.youtube.com/watch?v=p74282nDMX8)**

---

**Q(7): Any advice on things you want your interns at AirBnB to be good at when they're applying?**

---

_You don't have to reply to all of those, take the ones you want!_

**Comment by lencioni** [comment]
Thanks for the questions! Will you please break these all out into separate issues so they can be more easily found by others?

**Comment by evenstensberg** [comment]
Sure!
