### ISSUE TITLE
How do you proceed the back-end logic with Machine Learning to Front-End?

### ISSUE THREAD

**Issue by evenstensberg** [lencioni/ama#3]
## How do you proceed the back-end logic with Machine Learning to Front-End?

 Is there any key differences in terms of passing data into your React/Database components?

**Comment by lencioni** [comment]
Unfortunately, I am not familiar with this so I'm not really sure. I imagine that it would either be bootstrapped on the page from the server, or retrieved via an AJAX endpoint like other data.
