### ISSUE TITLE
How did you start of with programming?

### ISSUE THREAD

**Issue by evenstensberg** [lencioni/ama#5]

**Comment by lencioni** [comment]
I was fortunate enough to have a computer when I was pretty young. I grew up in rural Minnesota, where there wasn't a lot of things to do, so I ended up spending a lot of time playing games on my computer. After I ran out of games, I kept poking around to see what else the computer could do, and I discovered QBasic. I had a friend who lived nearby who also had a computer, so we learned how to program together--teaching each other what we learned as we went.

I bought a book about programming in QBasic, and a calling card to dial into some BBSes to download and learn from other people's programs. Then we finally got the internet and things really took off. I learned an obscure language called C-- (C minus minus) and eventually started doing programming. I spent a lot of years writing PHP, HTML, CSS, and JS and just kept building things. I haven't written any PHP in years now though.

I typically get bored of things pretty quickly, but I've never gotten bored of programming. Even after 20+ years I still find it infinitely interesting. I love the combination of problem solving, abstract thinking, and creating things that programming requires.
