### ISSUE TITLE
Can you mention some of the technologies Airbnb use besides React?

### ISSUE THREAD

**Issue by evenstensberg** [lencioni/ama#6]
#### Can you mention some of the technologies Airbnb use besides React?

Extra Question:
**Are you doing something similar to what Netflix do in their code? [Keynote from nodeJS](https://www.youtube.com/watch?v=p74282nDMX8)**

**Comment by lencioni** [comment]
I'm on the web infra team, so my answer is really skewed toward that area of our stack. Here are some of the things are are using that come to mind:
- Ruby on Rails
- Sass (SCSS syntax) -- [CSS styleguide](https://github.com/airbnb/css)
- PostCSS (with autoprefixer and a few other plugins)
- SCSS-Lint
- ESLint -- [JS styleguide](https://github.com/airbnb/javascript)
- Babel -- [here's our preset](https://github.com/airbnb/babel-preset-airbnb)
- React
- Alt (@goatslacker, the creator of Alt, is on my team. We are also looking into Redux right now.)
- Browserify (although I'm investigating webpack at the moment)
- GitHub enterprise

I don't know how up to date this is, but there's an [Airbnb stack on StackShare](http://stackshare.io/airbnb/airbnb) you can peruse as well.
