### ISSUE TITLE
Any advice on things you want your interns at Airbnb to be good at when they're applying?

### ISSUE THREAD

**Issue by evenstensberg** [lencioni/ama#7]

**Comment by lencioni** [comment]
I'm pretty new to the Airbnb team, and I haven't really interacted with the people hiring interns so I'm not really able to comment on that much. But, things that I would look for are qualities that are good for any software engineer: **ability to learn quickly, ability to communicate effectively, and grit**.

Beyond that I think that fundamentals (e.g. computer science, JavaScript, CSS, browsers) are important, and specific libraries (e.g. React, Angular, Ember, Backbone) are unimportant.
