### ISSUE TITLE
What's your proudest achievement outside of anything work related?

### ISSUE THREAD

**Issue by gdborton** [lencioni/ama#9]
^

**Comment by lencioni** [comment]
I rarely think of things that I've done as achievements and I don't usually characterize myself as being proud, but I think the thing I've done that probably comes closest to answering your question is when I edited my senior thesis down to less than 20 pages, submitted it to Theta Alpha Kappa, and won the [Albert Clark Award for best undergraduate essay in the world](http://www.thetaalphakappa.tcu.edu/scholarships_awards/clark_awards.html). My paper was published in the Journal of Theta Alpha Kappa, and [I've recently reposted it on Medium](https://medium.com/@lencioni/total-kenosis-true-shunyata-and-the-plerotic-self-of-thomas-merton-and-masao-abe-d3b848a06e60#.q9mf1cj8s) (and added an illustration), if you care to get nerdy.
